###
POST  http://localhost:30003/signup
Content-Type: application/json

{
    "email":"ii197@gmail.com",
    "username":"ii",
    "password":"Indra@321"

}



###
POST  http://localhost:30003/login
Content-Type: application/json

{
    "username":"ii",
    "password":"Indra@321"

}



###
POST  http://localhost:30003/forgot-password
Content-Type: application/json

{
    
  "email":"indrasena197@gmail.com"
}



###
POST  http://localhost:30003/reset-password
Content-Type: application/json

{
    
  "email":"indrasena197@gmail.com",
  "newPassword":"indrasena"
}


###
POST http://localhost:30003/p
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpIiwiaWF0IjoxNzIxMjcwNjAyfQ.GwLitCaOhGfN5vNJvFa4PSuT0OjblMZ5pyqAkD2cNTs
Content-Type: application/json

{
  "title":"ffdfd",
  "content":"Fddfddssbvx"
}



###
GET  http://localhost:30003/posts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpIiwiaWF0IjoxNzIxMjcwNjAyfQ.GwLitCaOhGfN5vNJvFa4PSuT0OjblMZ5pyqAkD2cNTs




###
PUT   http://localhost:30003/post/6697fba39c3590f934a44fc8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpIiwiaWF0IjoxNzIxMjcwNjAyfQ.GwLitCaOhGfN5vNJvFa4PSuT0OjblMZ5pyqAkD2cNTs 
Content-Type: application/json

{
  "title":"sfsjjjjjjjjjjjjjjjjdf",
  "content":"fdsfdsf"
}

###
DELETE   http://localhost:30003/post/66988208dbe3b34b49ef9700
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpIiwiaWF0IjoxNzIxMjcwNjAyfQ.GwLitCaOhGfN5vNJvFa4PSuT0OjblMZ5pyqAkD2cNTs





###
POST   http://localhost:30003/post/like/66988208dbe3b34b49ef9700
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpIiwiaWF0IjoxNzIxMjcwNjAyfQ.GwLitCaOhGfN5vNJvFa4PSuT0OjblMZ5pyqAkD2cNTs






###
POST    http://localhost:30003/post/comment/669882e51638d2ad03cae01c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpIiwiaWF0IjoxNzIxMjcwNjAyfQ.GwLitCaOhGfN5vNJvFa4PSuT0OjblMZ5pyqAkD2cNTs
Content-Type: application/json

{
  "text":"gsdfg"
}
